### ISSUE TITLE
[SUPORTE - WEB] atender chamados e adicionar solução

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#10]
🚀 Registro de chamados
---
O cliente deseja cadastro de chamados para acompanhamento dos problemas levantados e suas respectivas soluções, para que, a partir de uma base de dados estabelecida, consiga evitar retrabalhos e consultar soluções cujo resultado foi verificado. 
>💡 Esta tarefa se refere à criação da página para atendimento de chamados (variação da tela de detalhes do chamado voltado para o usuário suporte, com layout componentizado)

#### Expectativa de finalização
Página contendo cabeçalho, rodapé e o conteúdo principal que possibilite a visualização dos detalhes do chamado e com opção para atendimento do chamado, alterando seu status.
> Informações adicionais: **utilizar React e, se possível, Styled Components**

#### Solução proposta
- [x] Criação do template, reutilizando componentes criados anteriormente para tela de detalhe do chamado

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by ThHenrique** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página de login: React, react-router-dom, axios, CSS, VS Code.

### 🔨 Componentes criados:

Para o desenvolvimento da página de login do usuário foram criados os seguintes componentes: TicketComments, StatusTicket, PriorityLevelBadge, TicketAddComment, e TicketCommentSupport.

### 📸 Prints da tela montada:

Página de login:

WEB
![image](https://user-images.githubusercontent.com/58437896/163187862-216ec6e1-91ca-4cf6-b4d7-c97cd2780e06.png)

MOBILE
![image](https://user-images.githubusercontent.com/58437896/163188034-7f33ba4b-e9f0-4f13-a61b-3b739d688b55.png)

**Comment by ThHenrique** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página de login: React, react-router-dom, axios, CSS, VS Code.

### 🔨 Componentes criados:

Para o desenvolvimento da página de login do usuário foram criados os seguintes componentes: TicketComments, StatusTicket, PriorityLevelBadge, TicketAddComment, e TicketCommentSupport.

### 📸 Prints da tela montada:

Página de login:

WEB
![image](https://user-images.githubusercontent.com/58437896/163187862-216ec6e1-91ca-4cf6-b4d7-c97cd2780e06.png)

MOBILE
![image](https://user-images.githubusercontent.com/58437896/163188034-7f33ba4b-e9f0-4f13-a61b-3b739d688b55.png)
