### ISSUE TITLE
[FRONT] Refinamento final

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#105]
GERAL
---
- [x] Trocar cor do texto do botão (de novo chamado, por ex., é branco no Figma, no site tá cinzinha)
- [x] Colocar a setinha do select um pouco mais pra dentro (aumentar padding na direita)

DETALHES DO CHAMADO
- [x] Colocar os inputs como "desabilitados"

| Figma     | ![image](https://user-images.githubusercontent.com/69374340/171429531-9834cf84-9cf3-463c-89a5-4a8a11a4ad0c.png) |
| :----------: | :------------------: |
| Aplicação | ![image](https://user-images.githubusercontent.com/69374340/171429375-1dd8f211-8d8c-4243-9e98-fee4f3585edf.png) |

**Comment by MariaGabrielaReis** [comment]
FLUXO SUPORTE
---
HOME
- [ ] No select, ao invés de escrever só "abertos" e "fechados", trocar por "Chamados abertos" e "Chamados fechados"
- [ ] Adicionar linha divisória entre os resultados da busca, diminuir porcentagem da coluna de data e de prioridade e aumentar a de título do chamado

| Figma     |   ![image](https://user-images.githubusercontent.com/69374340/171423405-2e5d39a2-9d47-4118-91ce-869401fb8071.png) |
| :----------: | :------------------: |
| Aplicação | ![image](https://user-images.githubusercontent.com/69374340/171425511-295dd325-c46a-4318-b766-18807768186b.png) |

DETALHES DO CHAMADO
- [ ] Aumentar tamanho da caneta e do ícone de confirmar edição de prioridade (o ideal é que a badge e a caneta tenham a mesma altura)

| Figma     |   Aplicação  |
| :----------: | :--------------: |
|![image](https://user-images.githubusercontent.com/69374340/171427878-5a8f2025-fda8-4d82-bb63-a2bc8f5023f2.png) | ![image](https://user-images.githubusercontent.com/69374340/171427684-791765d1-ce6d-4c19-bcde-551807f8ad1f.png) |

- [ ] Verificar esquema de cores dos textos (parecem mais azulados do que acinzentados)

| Figma     | ![image](https://user-images.githubusercontent.com/69374340/171426322-29209901-84a8-4875-a186-676e661450d1.png) |
| :----------: | :------------------: |
| Aplicação | ![image](https://user-images.githubusercontent.com/69374340/171426185-8f2cb7fc-c02c-417c-b6a4-0c5fbc2c8f89.png) |

- [ ] Tirar borda do botão de fechar chamado
- [ ] Colocar descrição (tipo popover) quando passar o mouse por cima do check de transformar comentário em solução com o texto "adicionar este comentário como solução do chamado"
- [ ] Aumentar botão de enviar comentário e ajustar esquema de cores

| Figma     | ![image](https://user-images.githubusercontent.com/69374340/171427348-bb2f1f7e-95ff-4379-9815-1c70635d2312.png) |
| :----------: | :------------------: |
| Aplicação | ![image](https://user-images.githubusercontent.com/69374340/171427036-6a4081a1-ef1b-420b-a269-e2da81716daa.png) |

**Comment by otaviopane** [comment]
> ## GERAL
> * [x]  Trocar cor do texto do botão (de novo chamado, por ex., é branco no Figma, no site tá cinzinha)
> * [x]  Colocar a setinha do select um pouco mais pra dentro (aumentar padding na direita)
> 
> DETALHES DO CHAMADO
> 
> * [x]  Colocar os inputs como "desabilitados"
> 
> Figma	![image](https://user-images.githubusercontent.com/69374340/171429531-9834cf84-9cf3-463c-89a5-4a8a11a4ad0c.png)
> Aplicação	![image](https://user-images.githubusercontent.com/69374340/171429375-1dd8f211-8d8c-4243-9e98-fee4f3585edf.png)

### Ajustado cor dos inputs como "desabilitado"
![image](https://user-images.githubusercontent.com/58819253/171526813-b0ecf781-8e96-48bc-a13a-f397c63ca225.png)

### Ajustado cor do texto dos botões para branco
![image](https://user-images.githubusercontent.com/58819253/171526884-15668805-811e-4236-89d8-bffc4ff7db7b.png)

### Ajustado posição da seta dos selects
![image](https://user-images.githubusercontent.com/58819253/171526964-fb9a3523-0f49-465e-942a-f9173c642314.png)

**Comment by otaviopane** [comment]
> ## FLUXO COMUM
> HOME
> 
> * [ ]  Busca por título do chamado (integração)
> * [x]  Trocar cor e adicionar ícone no botão de busca por título de chamado
> 
> CADASTRO DE CHAMADO
> 
> * [ ]  Permitir cadastrar um chamado sem equipamento
> 
> DETALHES DO CHAMADO
> 
> * [x]  Colocar tag de solução em maiúsculo
> * [x]  Colocar a cor do nome do suporte da mesma cor de fundo da textarea de descrição da solução
> * [ ]  Adicionar contagem de votos aos botões de voto
> * [x] Alinhar à esquerda os botões de voto
> 
> | Figma     |   ![image](https://user-images.githubusercontent.com/69374340/171424638-c22c31c6-8b7b-4ada-ae2e-a60c8afa556a.png) |
> | :----------: | :------------------: |
> | Aplicação | ![image](https://user-images.githubusercontent.com/69374340/171425016-0424c9f3-47bb-4192-a846-595841f0b800.png) |

> EDIÇÃO DE PERFIL
> * [ ]  Colocar no header a opção de logout ("Olá, fulaninho" permanece e no dropdown só tem o logout)
> * [ ]  Alterar ordem dos campos (não precisa mexer nas questões de desabilitado ou não, isso tá certinho)

> | Figma     | Aplicação         |
> | :----------: | :------------------: |
> | ![image](https://user-images.githubusercontent.com/69374340/171421148-2d5e9b41-570b-4824-957f-257df36e7c35.png) | ![image](https://user-images.githubusercontent.com/69374340/171420785-98cc19b0-7600-43d2-9842-a10f4fd1a9aa.png) |

### Trocar cor e adicionar ícone no botão de busca por título de chamado 
![image](https://user-images.githubusercontent.com/58819253/171530121-0a67a7dd-9976-463b-b8ee-cb4eb10ecc04.png)

### Colocar tag de solução em maiúsculo
![image](https://user-images.githubusercontent.com/58819253/171530379-c634307f-6f86-4026-8518-f53fc6c7c012.png)

### Colocar a cor do nome do suporte da mesma cor de fundo da textarea de descrição da solução
![image](https://user-images.githubusercontent.com/58819253/171539524-2c7de150-9bfd-431d-b9ea-b02d0eed7785.png)

**Comment by otaviopane** [comment]
> ## FLUXO SUPORTE
> HOME
> 
> * [x]  No select, ao invés de escrever só "abertos" e "fechados", trocar por "Chamados abertos" e "Chamados fechados"
> * [ ]  Adicionar linha divisória entre os resultados da busca, diminuir porcentagem da coluna de data e de prioridade e aumentar a de título do chamado
> 
> Figma	![image](https://user-images.githubusercontent.com/69374340/171423405-2e5d39a2-9d47-4118-91ce-869401fb8071.png)
> Aplicação	![image](https://user-images.githubusercontent.com/69374340/171425511-295dd325-c46a-4318-b766-18807768186b.png)
> DETALHES DO CHAMADO
> 
> * [ ]  Aumentar tamanho da caneta e do ícone de confirmar edição de prioridade (o ideal é que a badge e a caneta tenham a mesma altura)
> 
> Figma	Aplicação
> ![image](https://user-images.githubusercontent.com/69374340/171427878-5a8f2025-fda8-4d82-bb63-a2bc8f5023f2.png)	![image](https://user-images.githubusercontent.com/69374340/171427684-791765d1-ce6d-4c19-bcde-551807f8ad1f.png)
> * [ ]  Verificar esquema de cores dos textos (parecem mais azulados do que acinzentados)
> 
> Figma	![image](https://user-images.githubusercontent.com/69374340/171426322-29209901-84a8-4875-a186-676e661450d1.png)
> Aplicação	![image](https://user-images.githubusercontent.com/69374340/171426185-8f2cb7fc-c02c-417c-b6a4-0c5fbc2c8f89.png)
> * [ ]  Tirar borda do botão de fechar chamado
> * [ ]  Colocar descrição (tipo popover) quando passar o mouse por cima do check de transformar comentário em solução com o texto "adicionar este comentário como solução do chamado"
> * [ ]  Aumentar botão de enviar comentário e ajustar esquema de cores
> 
> Figma	![image](https://user-images.githubusercontent.com/69374340/171427348-bb2f1f7e-95ff-4379-9815-1c70635d2312.png)
> Aplicação	![image](https://user-images.githubusercontent.com/69374340/171427036-6a4081a1-ef1b-420b-a269-e2da81716daa.png)

### No select, ao invés de escrever só "abertos" e "fechados", trocar por "Chamados abertos" e "Chamados fechados"
![image](https://user-images.githubusercontent.com/58819253/171762158-176ba2ba-f326-49e5-87fd-151e346d2ee4.png)

**Comment by otaviopane** [comment]
> ## FLUXO ADMIN
> HOME
> 
> * [x]  Não permitir busca vazia
> * [x]  Colocar os departamentos em português e em letra minúscula se não for sigla (incluindo o "Sem departamento")
> * [x]  Colocar tamanho das colunas "fixo" e aplicar `text-overflow: ellipsis;`, pra não mudar a configuração da tabela quando filtra por cargos ou na responsividade:
> 
> Web Mobile
> ![image](https://user-images.githubusercontent.com/69374340/171431083-d4c91b72-1bd6-462a-9ee4-b8f310ca07a8.png)	![image](https://user-images.githubusercontent.com/69374340/171431007-cb137387-385c-4b7a-bd72-ddc01ee8cf63.png)
> ![image](https://user-images.githubusercontent.com/69374340/171431270-a1359040-6d96-4278-b3ba-c28b22257448.png)	![image](https://user-images.githubusercontent.com/69374340/171431349-56b449db-91f5-4f77-a16e-ecdba823386d.png)
> * [ ]  Busca por nome do equipamento
> * [ ]  Filtrar equipamento por departamento
> * [ ]  Trocar nome do botão de "Cadastrar Equipamento" para "Cadastrar equipamento"
> 
> DETALHES DO EQUIPAMENTO
> 
> * [ ]  Trocar botões de "Excluir" e "Editar" por "Excluir equipamento" e "Confirmar alterações"
> 
> CADASTRO DE USUÁRIO
> 
> * [ ]  Trocar título da tela de "Cadastre a conta" para "Cadastro de usuário"

### Parece que já estava não permitindo busca vazia

### Coloquei os departamentos em português e em letra minúscula se não for sigla (incluindo o "Sem departamento")
![image](https://user-images.githubusercontent.com/58819253/172029318-58cf2a0c-53f5-4c5f-b73a-e35e39eb2195.png)

### Colocado tamanho das colunas "fixo" e aplicar `text-overflow: ellipsis;`, pra não mudar a configuração da tabela quando filtra por cargos ou na responsividade:
#### Usuários
![image](https://user-images.githubusercontent.com/58819253/172029847-3cd181d7-9e79-4b8f-8352-5963fe4dbe22.png)
![image](https://user-images.githubusercontent.com/58819253/172029828-bb0bf6df-929e-43d6-9138-a19bb2907a82.png)
#### Equipamentos
![image](https://user-images.githubusercontent.com/58819253/172030104-721be8d6-96ab-47c1-b3be-7ab0eeb5ae50.png)
![image](https://user-images.githubusercontent.com/58819253/172030098-bca2247d-2174-4df8-8314-75f153b197f0.png)
