### ISSUE TITLE
[ADMIN - INTEGRAÇÃO] cadastro de usuários

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#14]
🚀 Cadastro e login de usuários
---
O cliente deseja cadastro de 3 tipos de usuários: "comum", "suporte" e "administrador", para que cada perfil tenha suas funcionalidades personalizadas. 
>💡 Esta tarefa se refere ao consumo do endpoint destinado ao cadastro de usuários comuns e suportes pelo usuário administrador

#### Expectativa de finalização
Página dinâmica e funcional, que possibilite a criação de usuários comuns e suporte pelo usuário administrador, tratando qualquer exceção que possa ser gerada (tratamento de erros como "não foi possível cadastrar o usuário por conta de...", etc)

> Informações adicionais: ...

#### Solução proposta
- [ ] Consumo do endpoint disponível para criação de usuários comuns
- [ ] Consumo do endpoint disponível para criação de usuários suportes
- [ ] Tratamento de erros comuns que podem ocorrer na criação de usuários pelo administrador

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [ ] Documentação
- [ ] Verificar funcionamento (atender as expectativas para tarefa)
- [ ] Code Review (abertura e aprovação de PR)
- [ ] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página: React, React-router-dom, CSS, VS Code.

### 🔨 Componentes utilizados:

Button, ChoiceField, TextField, Footer e Header.

### 📸 Print da tela montada:

![image]()
