### ISSUE TITLE
[COMUM - INTEGRAÇÃO] lista de chamados

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#15]
🚀 Registro de chamados
---
O cliente deseja cadastro de chamados para acompanhamento dos problemas levantados e suas respectivas soluções, para que, a partir de uma base de dados estabelecida, consiga evitar retrabalhos e consultar soluções cujo resultado foi verificado. 
>💡 Esta tarefa se refere ao consumo do endpoint destinado à listagem de chamados de um usuário comum

#### Expectativa de finalização
Página dinâmica e funcional, que possibilite a listagem dos chamados do usuário que abriu aquela sessão na plataforma, tratando de possíveis exceções como "falha ao carregar chamados", "nenhum chamado cadastrado ainda", etc

> Informações adicionais: ...

#### Solução proposta
- [x] Consumo do endpoint disponível para listagem de chamados de um usuário específico
- [x] Tratamento de erros comuns que podem ocorrer no consumo dos dados

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página: React, VS Code e Axios.

### 🔨 Rota consumida:

```https://help-duck-tickets.herokuapp.com/tickets/user/{userId}```

### 📸 Print da tela montada:

![image](https://user-images.githubusercontent.com/78885451/163412681-d430857d-4fc4-4201-9e3e-b6a7d850ea83.png)
