### ISSUE TITLE
[ADMIN - WEB] cadastro de usuários

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#2]
🚀 Cadastro e login de usuários
---
O cliente deseja cadastro de 3 tipos de usuários: "comum", "suporte" e "administrador", para que cada perfil tenha suas funcionalidades personalizadas. 
>💡 Esta tarefa se refere à criação da página de cadastro de usuários do administrador (layout com componentização)

#### Expectativa de finalização
Página contendo cabeçalho, rodapé e o conteúdo principal que possibilite a criação de novos usuários por parte de um usuário administrador.
> Informações adicionais: **utilizar React e, se possível, Styled Components**

#### Solução proposta
- [x] Criação do template com os componentes já existentes

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [ ] Documentação
- [ ] Verificar funcionamento (atender as expectativas para tarefa)
- [ ] Code Review (abertura e aprovação de PR)
- [ ] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página: React, CSS, VS Code.

### 🔨 Componentes criados:

Para o desenvolvimento da página foram criados os seguintes componentes: 
ChoiceField. 

Outros componentes foram utilizados além dos componentes criados, sendo eles: 
Button, ChoiceField, TextField, Footer e Header.

### 📸 Print da tela montada:

![image]()
