### ISSUE TITLE
[SUPORTE -  INTEGRAÇÃO] lista de chamados

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#20]
🚀 Registro de chamados
---
O cliente deseja cadastro de chamados para acompanhamento dos problemas levantados e suas respectivas soluções, para que, a partir de uma base de dados estabelecida, consiga evitar retrabalhos e consultar soluções cujo resultado foi verificado. 
>💡 Esta tarefa se refere ao consumo do endpoint destinado à listagem de chamados do usuário suporte

#### Expectativa de finalização
Página dinâmica e funcional, que possibilite a listagem de todos os chamados, tratando de possíveis exceções como "falha ao carregar chamados", "nenhum chamado cadastrado ainda", etc

> Informações adicionais: ...

#### Solução proposta
- [x] Consumo do endpoint disponível para listagem geral de chamados
- [x] Tratamento de erros comuns que podem ocorrer no consumo dos dados

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página: React, VS Code e Axios.

### 🔨 Rota consumida:

```https://help-duck-tickets.herokuapp.com/tickets```

### 📸 Print da tela montada:

![image](https://user-images.githubusercontent.com/78885451/163414021-282003de-6484-42e6-a823-ab98c7d536a2.png)
