### ISSUE TITLE
[SUPORTE - INTEGRAÇÃO] atender chamados e adicionar solução

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#21]
🚀 Registro de chamados
---
O cliente deseja cadastro de chamados para acompanhamento dos problemas levantados e suas respectivas soluções, para que, a partir de uma base de dados estabelecida, consiga evitar retrabalhos e consultar soluções cujo resultado foi verificado. 
>💡 Esta tarefa se refere ao consumo do endpoint destinado ao atendimento de chamados

#### Expectativa de finalização
Página dinâmica e funcional, que possibilite a visualização dos detalhes do chamado, com opção para atendimento do chamado, alterando seu status, além de tratar possíveis exceções como "falha ao carregar chamado", "falha ao atender chamado", etc

> Informações adicionais: ...

#### Solução proposta
- [x] Consumo do endpoint disponível para atendimento de chamados
- [x] Tratamento de erros comuns que podem ocorrer no consumo dos dados

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by ThHenrique** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página de login: React, react-router-dom, axios, CSS, VS Code.

### 🔨 Componentes criados:

Para o desenvolvimento da página de login do usuário foram criados os seguintes componentes: TicketComments, StatusTicket, PriorityLevelBadge, TicketAddComment, e TicketCommentSupport.

### 📸 Prints da tela montada:

Página de login:

WEB
![image](https://user-images.githubusercontent.com/58437896/163187862-216ec6e1-91ca-4cf6-b4d7-c97cd2780e06.png)

MOBILE
![image](https://user-images.githubusercontent.com/58437896/163188034-7f33ba4b-e9f0-4f13-a61b-3b739d688b55.png)
