### ISSUE TITLE
[COMUM - INTEGRAÇÃO] cadastrar chamado

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#23]
🚀 Registro de chamados
---
O cliente deseja cadastro de chamados para acompanhamento dos problemas levantados e suas respectivas soluções, para que, a partir de uma base de dados estabelecida, consiga evitar retrabalhos e consultar soluções cujo resultado foi verificado. 
>💡 Esta tarefa se refere ao consumo do endpoint destinado ao cadastro de chamados

#### Expectativa de finalização
Página dinâmica e funcional, que possibilite a criação de um novo chamado, tratando de possíveis exceções como "falha ao criar chamado", etc

> Informações adicionais: ...

#### Solução proposta
- [ ] Consumo do endpoint disponível para cadastro de chamados
- [ ] Tratamento de erros comuns que podem ocorrer no consumo dos dados

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página: React, React-router-dom, CSS, VS Code.

### 🔨 Componentes utilizados:

Button, ChoiceField, TextField, Footer e Header.

### 📸 Print da tela montada:

![image](https://user-images.githubusercontent.com/58819253/163290641-8fe2e45f-2204-443e-93b6-68c074ba4caf.png)
