### ISSUE TITLE
[COMUM - WEB] cadastrar chamado

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#4]
🚀 Registro de chamados
---
O cliente deseja cadastro de chamados para acompanhamento dos problemas levantados e suas respectivas soluções, para que, a partir de uma base de dados estabelecida, consiga evitar retrabalhos e consultar soluções cujo resultado foi verificado. 
>💡 Esta tarefa se refere à criação da página de cadastro de chamados (layout com componentização)

#### Expectativa de finalização
Página contendo cabeçalho, rodapé e o conteúdo principal que possibilite a criação de um novo chamado.
> Informações adicionais: **utilizar React e, se possível, Styled Components**

#### Solução proposta
- [x] Criação do template

---
#### Espaço para anotações do responsável pela tarefa
...

#### Capturas de tela (caso de tarefa com alteração no layout)
...

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página: React, CSS, VS Code.

### 🔨 Componentes criados:

Outros componentes foram utilizados além dos componentes criados, sendo eles: 
Button, ChoiceField, TextField, Footer e Header.

### 📸 Print da tela montada:

![image]()
