### ISSUE TITLE
[ADMIN - WEB / INTEGRAÇÃO] home

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#40]

**Comment by gioliveirass** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o desenvolvimento da página: React, VS Code e Axios.

### 🔨 Rota consumida:

```https://help-duck-users.herokuapp.com/users/```

### 📸 Print da tela montada:

![image](https://user-images.githubusercontent.com/78885451/163414435-195c3ba2-ef61-4d5d-b426-21a68ea0da31.png)
