### ISSUE TITLE
[FRONT] Esqueci a senha e voltar da criação de chamado

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#45]
🚀 Refinamento de detalhes (frutos da Review)
---

#### Tarefas
- [x] Adicionar fluxo para "esqueci a senha" na tela de login (ex: alerta simples)
- [x] Adicionar função no botão de voltar na tela de criação de chamados (voltar à tela inicial/home)

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
# Documentação

## 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante a aplicação da responsividade: React, Typescript, CSS e HTML.

## 📸 Print das atividades desenvolvidas:

#### 🔸 Criação do alerta de "esqueceu a senha?":
![image](https://user-images.githubusercontent.com/58819253/167966039-9ee05357-90f4-4ba5-9dd1-f0802d8c9951.png)

#### 🔸  Adicionada a função de voltar na tela de criação de chamados:
![image](https://user-images.githubusercontent.com/58819253/167966231-da393be8-a02a-4451-b223-8ca3e6263991.png)
