### ISSUE TITLE
[FRONT] Responsividade

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#46]
🚀 Sistema Responsivo
---
O cliente deseja responsividade ao site para que seja capaz de utilizar o sistema em qualquer dispositivo de forma que ele se adapte a cada diferente dimensão de tela. 
>💡 Esta tarefa se refere a adição de responsividade à interface do sistema

#### Expectativa de finalização
Todas as telas até o momento cm responsividade aplicada, gerando visualizações do sistema em computadores de mesa, notebooks, tablets e telemóveis, visando replicar os layouts idealizados no Figma:
- [Tela de login](https://www.figma.com/file/aSJvHfQ30FyNOR2ZVbvBzw/HelpDuck?node-id=28%3A132)
- [Tela de cadastro de usuários](https://www.figma.com/file/aSJvHfQ30FyNOR2ZVbvBzw/HelpDuck?node-id=99%3A70) (necessita de revisão)
- [Tela inicial de usuários comuns e suporte](https://www.figma.com/file/aSJvHfQ30FyNOR2ZVbvBzw/HelpDuck?node-id=22%3A89)
- [...Tela inicial de usuários administradores]() (necessita de criação)
- [Tela de cadastro de chamado](https://www.figma.com/file/aSJvHfQ30FyNOR2ZVbvBzw/HelpDuck?node-id=26%3A247)
- [Tela de detalhes do chamado (usuário comum)](https://www.figma.com/file/aSJvHfQ30FyNOR2ZVbvBzw/HelpDuck?node-id=22%3A187) (necessita de revisão)
- [...Tela de detalhes do chamado (usuário suporte)]() (necessita de criação)
- [...Tela de edição de perfil]() (necessita de criação)

#### Solução proposta
- [x] Criação dos layouts responsivos faltantes no Figma
    - [x] Revisão da **tela de cadastro de usuários**
    - [x] Criar **tela inicial de usuários administradores**
    - [x] Criar **tela de detalhes do chamado (usuário comum)**
    - [x] Criar **tela de detalhes do chamado (usuário suporte)**
- [x] Aplicação de responsividade nas telas:
    - [x] Aplicar responsividade da **HEADER**
    - [x] Tela de **login**
    - [x] Tela **inicial de usuários comuns e suporte**
    - [x] Tela **inicial de usuários administradores**
    - [x] Aplicar responsividade do **GRID**
    - [x] Tela de **cadastro de chamado**
    - [x] Tela de **detalhes do chamado (usuário comum)**
    - [x] Tela de **detalhes do chamado (usuário suporte)**
    - [x] Tela de **cadastro de usuários**

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
# Criação dos layouts responsivos faltantes no Figma

## Revisão da tela de cadastro de usuários

![image](https://user-images.githubusercontent.com/78885451/167137005-554422c4-3be6-4428-a51f-2cced0b0599d.png)

## Criar tela inicial de usuários administradores

![image](https://user-images.githubusercontent.com/78885451/167137125-25e20a14-a678-4f33-81d0-1f5f44d126a9.png)

## Criar tela de detalhes do chamado (usuário comum/suporte)

![image](https://user-images.githubusercontent.com/78885451/167137312-27702195-80d6-4011-9d66-0e04e4ae452a.png)

# Aplicação de responsividade nas telas

## Aplicar responsividade da HEADER

![image](https://user-images.githubusercontent.com/78885451/167137684-9216e40b-5e9b-436b-82d5-bc743f816990.png)

## Tela de login

![image](https://user-images.githubusercontent.com/78885451/167137511-d60c075a-b417-4756-9405-d6ba01d4f41c.png)

## Tela inicial de usuários comuns e suporte

![image](https://user-images.githubusercontent.com/78885451/167137651-7bdc1d75-e130-45c9-b9fe-30c97bdc7768.png)

## Tela inicial de usuários administradores

![image](https://user-images.githubusercontent.com/78885451/167138487-f124f18f-81e9-4954-a4c6-e5024dacbb5c.png)

## Aplicar responsividade do GRID

![image](https://user-images.githubusercontent.com/78885451/167137839-074355c6-6fbe-48ed-9880-94ae22ad7334.png)
![image](https://user-images.githubusercontent.com/78885451/167138236-5452da98-bc27-4b32-abcb-4ad0a0a21fcc.png)

## Tela de detalhes do chamado (usuário comum)

![image](https://user-images.githubusercontent.com/78885451/167137955-4d26e3a6-a499-4675-a46b-b8764200f48d.png)

## Tela de detalhes do chamado (usuário suporte)

![image](https://user-images.githubusercontent.com/78885451/167138081-449b6f5c-3f52-4d1f-a752-90e017453e68.png)

## Tela de cadastro de usuários

![image](https://user-images.githubusercontent.com/78885451/167138584-b4a71091-94f1-49be-a341-cb5efd1b2f07.png)
