### ISSUE TITLE
[FRONT] Edição de perfil

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#47]
🚀 Cadastro e login de usuários
---
O cliente deseja cadastro de 3 tipos de usuários: "comum", "suporte" e "administrador", para que cada perfil tenha suas funcionalidades personalizadas. 
>💡 Esta tarefa se refere à criação da página de edição de perfil do usuário (layout e integração)

#### Expectativa de finalização
Página funcional que permita ao usuário editar suas informações pessoais (como nome, login e senha), sendo ideal a utilização de tecnologias como **React** e **Styled Components** para replicar o layout componentizado como descrito neste [Figma](https://www.figma.com/file/aSJvHfQ30FyNOR2ZVbvBzw/HelpDuck?node-id=293%3A97).

#### Solução proposta
- [x] Criação do template
- [x] Integração da funcionalidade (consumo dos endpoints do backend)

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
# Documentação

## 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante a aplicação da responsividade: React, Typescript, CSS e HTML. Para a prototipação foi utilizado o Figma.

## 📸 Print das atividades desenvolvidas:

### 🔸 Criação e integração da página de edição de usuários

#### Visão do Administrador:
![image](https://user-images.githubusercontent.com/58819253/167750061-54d90c6a-7662-4e03-85aa-839c27b439e9.png)

#### Visão do Próprio usuário:
![image](https://user-images.githubusercontent.com/58819253/167749972-9ca7efae-7ed3-42b1-af56-6315baeac60b.png)
