### ISSUE TITLE
[FRONT] Implementar ordenação

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#51]

**Comment by ThHenrique** [comment]
# Documentação

## 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante a aplicação da ordenação: Axios, TypeScript, CSS e HTML. 

## 📸 Print das atividades desenvolvidas:

### 🔸 Listagem de chamados sem ordenação

![image](https://user-images.githubusercontent.com/58437896/168280227-7903182a-3ec6-4e09-8a3d-1144c26083cd.png)

- Para ordenar a tabela basta escolher pelo o que ordernar. Isso é feito selecionando (clicando) um campo da coluna no cabeçalho da tabela.

### 🔸 Listagem de chamados ordenado por título (decrescente)

![image](https://user-images.githubusercontent.com/58437896/168280397-01375a35-c9b7-4f33-a405-6d1ce1ca6885.png)

-  Selecionando a primeira vez é feito uma ordenação decrescente.

- Caso queira ordenar de forma crescente, basta selecionar o mesmo campo da coluna no cabeçalho da tabela.

### 🔸 Listagem de chamados ordenado por título (crescente)

![image](https://user-images.githubusercontent.com/58437896/168281745-ac63cc4a-5ad6-4eeb-9aca-e1415e82649d.png)

- O mesmo efeito é implementado para listagem de usuário, basta selecionar um campo da coluna no cabeçalho da tabela, como explicado anteriormente.

### 🔸 Listagem de chamados ordenado por nome (decrescente)

![image](https://user-images.githubusercontent.com/58437896/168282043-7675c91e-5a33-4d94-8ed9-47a1f75ba80b.png)

### 🔸 Listagem de chamados ordenado por nome (crescente)

![image](https://user-images.githubusercontent.com/58437896/168282942-a523142f-78b1-40df-acc7-2c9394af059e.png)

---
### 🔸 Remover ordenação

- A ordenação é removida após selecionar a mesma coluna três vezes, ou seja, após ser ordenada de forma decrescente e crescente.
