### ISSUE TITLE
[FRONT] Responsável do chamado

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#56]
colocar responsável do chamado - front (incrementar no figma)

![image](https://user-images.githubusercontent.com/69374340/167744270-90e46f06-b8e6-47c4-9a65-128eda37a3e6.png)
---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
# Documentação

## 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante a aplicação da responsividade: CSS e HTML. 

## 📸 Print do resultado

### 🔸 Com responsável

![image](https://user-images.githubusercontent.com/78885451/168292352-05b602d3-acc8-40e6-b0a1-a9b34681aaa7.png)

### 🔸 Sem responsável

![image](https://user-images.githubusercontent.com/78885451/168292494-65c693f3-db61-4db0-8bba-8458360fa528.png)
