### ISSUE TITLE
[FRONT] Tokens nas requisições

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#58]
🚀 Tokens nas requisições
---

- [x] Adicionar token na Header
- [x] Corrigir bugs

#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:
Foram utilizadas as seguintes tecnologias: Axios, VS Code, JavaScript.

### 📸 Print: 

Passando o token na Header:

![image](https://user-images.githubusercontent.com/78885451/167837350-1af7d5d9-8ad4-47cb-b478-f04067cd3f31.png)

![image](https://user-images.githubusercontent.com/78885451/167838118-8a358503-0ea4-4c15-b15e-0971ad867217.png)
