### ISSUE TITLE
[FRONT] CRUD de equipamentos

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#60]
🚀 CRUD de equipamentos
---

- [x] Tela de cadastro
- [x] Tela de listagem
- [x] Tela de edição
- [x]  Botão de exclusão

#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
# Documentação

## 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante a aplicação da responsividade: CSS e HTML. 

## 📸 Print das atividades desenvolvidas:

### 🔸 Listagem de equipamentos

![image](https://user-images.githubusercontent.com/78885451/168265817-ead42008-da0e-4037-945c-e476f02d5178.png)

### 🔸 Cadastro de equipamentos

![image](https://user-images.githubusercontent.com/78885451/168265930-c2d7552e-6c87-4a33-b66f-a49886285c07.png)

### 🔸 Edição e exclusão de equipamentos

![image](https://user-images.githubusercontent.com/78885451/168266040-d49bcb5a-e4a2-4a7a-bf38-fc959aa1353f.png)
