### ISSUE TITLE
[FRONT] Melhorias front

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#78]
Fazer melhorias em telas:

- [x] [LOGIN] - Padronizar botão de acordo com o [figma](https://www.figma.com/file/aSJvHfQ30FyNOR2ZVbvBzw/HelpDuck?node-id=28%3A46) (;
- [x] [EDIÇÃO DE EQP] - Alterar título da tela para "Detalhes do equipamento";
- [x] [EDIÇÃO DE USER - COMUM] - Alterar título da tela para "Edição de perfil";
- [x] [EDIÇÃO DE USER - ADMIN] - Alterar título da tela para "Detalhes do usuário";
- [x] [USER - CADASTRO, EDIÇÃO/DETALHES] Alinhar botões nas telas;
- [x] [EQP - CADASTRO, EDIÇÃO/DETALHES] Alinhar botões nas telas;
- [x] [CHAMADO - CADASTRO, EDIÇÃO/DETALHES] Alinhar botões nas telas;
- [x] [USER - CADASTRO, EDIÇÃO/DETALHES] Espaçamento entre títulos e seta (voltar)
- [x] [EQP - CADASTRO, EDIÇÃO/DETALHES] Espaçamento entre títulos e seta (voltar)
- [x] [CHAMADO - CADASTRO, EDIÇÃO/DETALHES] Espaçamento entre títulos e seta (voltar)
- [x] [USER - CADASTRO, EDIÇÃO/DETALHES] Responsividade
- [x] [EQP - CADASTRO, EDIÇÃO/DETALHES] Responsividade
- [x] [CHAMADO - CADASTRO, EDIÇÃO/DETALHES] Responsividade
- [x] [CADASTRO USER] - Alterar layout para o padrão de cadastros;
- [x] [CADASTRO DE CHAMADO] - Corrigir escrita da opção "malfuncionamento";

---
#### Definition of Done
- [ ] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
<h1 align="center"> Documentação 📄 </h1>

## Tecnologias utilizadas:
As seguintes tecnologias foram utilizadas para o desenvolvimento dessa tarefa: CSS, HTML, React.

## Prints dos Resultados:
![image](https://user-images.githubusercontent.com/58819253/171298154-15250c66-6d79-4a94-a1c1-6b77e75364be.png)
![image](https://user-images.githubusercontent.com/58819253/171298159-4b1b10d6-5d32-4211-ba9e-8d2dcbfbf006.png)
![image](https://user-images.githubusercontent.com/58819253/171298169-cb5b3e80-d6e0-424f-bc77-9b12e3021589.png)
![image](https://user-images.githubusercontent.com/58819253/171298177-7312a93b-2094-4cf9-a503-7f57716a5b9d.png)
![image](https://user-images.githubusercontent.com/58819253/171298187-fdea929a-1e0c-4abb-a2df-3051407a4932.png)

### Antes:
![image](https://user-images.githubusercontent.com/58819253/171298208-d1172d4b-2b28-4b95-a2b7-ce724ee401f7.png)
### Depois:
![image](https://user-images.githubusercontent.com/58819253/171298195-7378bd64-65a4-4982-b6d2-6634cf50015f.png)

### Antes:
![image](https://user-images.githubusercontent.com/58819253/171298322-7ef7ec73-63a5-4d41-b1b9-bab548672176.png)
### Depois:
![image](https://user-images.githubusercontent.com/58819253/171298340-49571628-6bac-4450-9ecc-eff37a7051ad.png)
