### ISSUE TITLE
[FRONT] Ordenação dos equipamentos

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#79]
[HOME - ADMIN] Ordenação por:

- [x] Nome;
- [x] Modelo;
- [x] Marca;
- [x] Tipo;
- [x] Departamento.

[HOME - ADMIN] Se necessário:
- [x] Corrigir responsividade

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align="center"> Documentação 📄 </h1>

## Tecnologias utilizadas:
As seguintes tecnologias foram utilizadas para o desenvolvimento dessa tarefa: CSS, HTML, React.

## Prints do Resultado

### ✏️ Ordenação por nome:

![image](https://user-images.githubusercontent.com/78885451/169171508-c1c75a92-50e1-4641-9a08-9a9aa839c534.png)

### ✏️ Ordenação por modelo:

![image](https://user-images.githubusercontent.com/78885451/169171552-190398b9-7b08-44d1-a916-e1a4f9cfce65.png)

### ✏️ Ordenação por marca:

![image](https://user-images.githubusercontent.com/78885451/169171593-98f9311e-a951-4d71-a436-75f2b629473c.png)

### ✏️ Ordenação por tipo:

![image](https://user-images.githubusercontent.com/78885451/169171625-ed2c5e61-8b18-4065-bc6c-e5f45d4f32f8.png)

### ✏️ Ordenação por departamento:

![image](https://user-images.githubusercontent.com/78885451/169171761-6449b9d0-794e-42ba-962b-3cf58e7740c3.png)
