### ISSUE TITLE
[FRONT] Alterar prioridade do chamado

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#80]
[DETALHES DO CHAMADO - SUPORTE]:

- [x] Adicionar opção para que o suporte possa alterar o prioridade do chamado.

- Quando abre os detalhes do chamado:
![image](https://user-images.githubusercontent.com/58437896/169538954-46128824-6bc2-4fce-aaa1-030413f63984.png)

- Quando clica no ícone de edição:
![image](https://user-images.githubusercontent.com/58437896/169539057-f342a804-aaf1-4eeb-95f4-8991fffd7bb5.png)

- Depois de escolher uma nova prioridade:
![image](https://user-images.githubusercontent.com/58437896/169539250-8e3621f1-86c7-4af2-b1ee-e3625c2cecf7.png)

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by otaviopane** [comment]
<h1 align="center"> Documentação 📄 </h1>

## Tecnologias utilizadas:
As seguintes tecnologias foram utilizadas para o desenvolvimento dessa tarefa: CSS, HTML, React.

## Prints do Resultado

### ✏️ Fluxo  da alteração da prioridade do chamado pelo suporte:
![image](https://user-images.githubusercontent.com/58819253/170848306-a7557109-17e9-4339-a40f-e73deef79071.png)
![image](https://user-images.githubusercontent.com/58819253/170848654-4e992218-9372-4fa1-a57b-6939218f282b.png)
![image](https://user-images.githubusercontent.com/58819253/170848662-8c31f3ef-b45f-4de0-8d28-6006add7f091.png)
![image](https://user-images.githubusercontent.com/58819253/170848669-57c171d9-b021-4920-8a70-c0add1875bbe.png)
![image](https://user-images.githubusercontent.com/58819253/170848675-978138b7-4ac8-4a00-838e-c0b6f9460872.png)
