### ISSUE TITLE
[FRONT] Adicionar informações ao chamado

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#81]
[DESTALHES E CADASTRO - CHAMADOS] Adicionar campo:

- [x] Departamento no cadastro de chamados;
- [x] Equipamento no cadastro de chamados;
- [x] Departamento nos detalhes do chamado;
- [x] Equipamento nos detalhes do chamado.
- [x] Data de fechamento do chamado

[DESTALHES E CADASTRO - CHAMADOS] Manter a responsividade nas telas:

- [x] Detalhes do chamado;
- [x] Cadastro do chamado.

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align='center'> Documentação </h1>

## Tecnologias utilizadas

As seguintes tecnologias foram utilizadas para o desenvolvimento dessa atividade: CSS, HTML, React, TypeScript.

## Prints dos resultados

Tela de cadastro de chamados

![image](https://user-images.githubusercontent.com/78885451/169629382-1d2ee59f-21a2-4530-9d00-bce5c9ca369f.png)


Tela de detalhes do chamado

![image](https://user-images.githubusercontent.com/78885451/169629356-2fb667e7-7d52-4f18-8484-cecaeae9fb42.png)

Responsividade da tela de cadastro de chamados

![image](https://user-images.githubusercontent.com/78885451/169629387-7967baea-10d9-4445-8a30-4735c43a38d7.png)

Responsividade da tela de detalhes do chamado

![image](https://user-images.githubusercontent.com/78885451/169629365-81c4595d-2180-4752-bc5e-dd5c640a524a.png)
