### ISSUE TITLE
[FRONT] Implementar buscas por título de chamado

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#83]
- [x] [CHAMADO] - Busca por título;

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align='center'> Documentação </h1>

Busca pelo título do chamado (ainda sem o filtro integrado pois não há essa funcionalidade no back):

![image](https://user-images.githubusercontent.com/78885451/171838624-6e5362d6-21cd-4056-b3fc-42f26f18aec5.png)

**Tecnologias utilizadas:** HTML, CSS, JavaScript, Axios
