### ISSUE TITLE
[FRONT] Editar senha

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#86]
[LOGIN]Usuário altera sua senha

- [x] [EDIÇÃO DE USER - COMUM] - Adicionar os campos para confirmação de senha anterior
- [x] [EDIÇÃO DE USER - COMUM] - Adicionar lógica para confirmação de senha anterior.

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align="center"> Documentação </h1>

Ao atualizar os próprios dados, a senha é solicitada:

![image](https://user-images.githubusercontent.com/78885451/170766460-68d3a7eb-0b46-4f8a-9f7a-f5c50f589660.png)

Quando o Admin atualiza os dados de outro usuário não requer solicitação de senha.

Quando clicar no botão de deletar, aparece uma confirmação:

![image](https://user-images.githubusercontent.com/78885451/170766848-e5e1cdab-8b40-40c6-abe0-fefe7831b2bd.png)

**Tecnologias utilizadas: ** CSS, HTML, React, Axios
