### ISSUE TITLE
[FRONT] Alinhamento de página

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#90]
- [x] Alinhar componentes da página com o header.

---
Definition of Done

- [ ]  Documentação
- [x]  Verificar funcionamento (atender as expectativas para tarefa)
- [x]  Code Review (abertura e aprovação de PR)
- [x]  Validação do cliente (caso necessário)

**Comment by MariaGabrielaReis** [comment]
![image](https://user-images.githubusercontent.com/58819253/170402325-bbb2bafa-1aec-404b-81bf-f7d37a6b0560.png)
![image](https://user-images.githubusercontent.com/58819253/170402357-e167df49-7a46-497d-9f0c-dd25d0342230.png)
![image](https://user-images.githubusercontent.com/58819253/170402393-c664b3c5-78b0-4abe-95c8-6493c98359e8.png)
![image](https://user-images.githubusercontent.com/58819253/170402445-032c2960-1aac-48e8-816d-8c1cdfa002ad.png)
![image](https://user-images.githubusercontent.com/58819253/170402465-8ce3f6fa-452d-4ee0-bc10-1a4f74fc9241.png)
![image](https://user-images.githubusercontent.com/58819253/170402491-7a3a3cac-d875-42c8-b659-d1aaaed5c40b.png)
![image](https://user-images.githubusercontent.com/58819253/170402512-f50fd7d7-b91b-42f7-a9b3-faac3e26ccc9.png)
![image](https://user-images.githubusercontent.com/58819253/170402535-6859e9ce-1f1c-45a5-bf38-ad229202be7b.png)
