### ISSUE TITLE
[FRONT - BACK] Avaliação da solução

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#92]
[SOLUÇÃO]

- [x] Implementar up vote down vote

**Comment by ThHenrique** [comment]
# Frontend, #100 

## Integrando a votação da solução, #92 


![image](https://user-images.githubusercontent.com/58437896/170107105-fbb73884-8d48-4361-bddc-8d87bda8300a.png)

- Em um chamado que contém uma solução podemos marcar a mesma como útil para mim ou não clicando nos botões em destaque na imagem acima (FOI ÚTIL PRA MIM | NÃO FOI ÚTIL PRA MIM)

![image](https://user-images.githubusercontent.com/58437896/170107455-e513ea62-c84c-436d-aba9-a6deb299b77d.png)

- Ao selecionar opção é realizado a requisição para o backend, salvando seu voto

![image](https://user-images.githubusercontent.com/58437896/170107599-9afa6e80-d230-4c43-91c6-90768054e071.png)

- Caso processo ocorra com sucesso, a área é ocultada. 


# BACKEND

## Método para adicionar um voto na solução, podendo marcar a solução como útil ou não.

- URL - ```<SolutionURL>```/solutions/vote

- payload:

```json
{
	"solutionId": "solutionId",
	"upVote": true,
	"downVote": false
}
```

**Comment by ThHenrique** [comment]
# Frontend, #100 

## Integrando a votação da solução, #92 


![image](https://user-images.githubusercontent.com/58437896/170107105-fbb73884-8d48-4361-bddc-8d87bda8300a.png)

- Em um chamado que contém uma solução podemos marcar a mesma como útil para mim ou não clicando nos botões em destaque na imagem acima (FOI ÚTIL PRA MIM | NÃO FOI ÚTIL PRA MIM)

![image](https://user-images.githubusercontent.com/58437896/170107455-e513ea62-c84c-436d-aba9-a6deb299b77d.png)

- Ao selecionar opção é realizado a requisição para o backend, salvando seu voto

![image](https://user-images.githubusercontent.com/58437896/170107599-9afa6e80-d230-4c43-91c6-90768054e071.png)

- Caso processo ocorra com sucesso, a área é ocultada. 


# BACKEND

## Método para adicionar um voto na solução, podendo marcar a solução como útil ou não.

- URL - ```<SolutionURL>```/solutions/vote

- payload:

```json
{
	"solutionId": "solutionId",
	"upVote": true,
	"downVote": false
}
```
