### ISSUE TITLE
[FRONT] Filtragem de usuários

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#93]
[USUÁRIO - ADMIN] Integração

Filtragem por cargo:
- [x] Admin;
- [x] Suporte;
- [x] Usuário comum.

**Comment by ThHenrique** [comment]
### Issue https://github.com/The-Bugger-Ducks/help-duck-web/issues/93

Conforme descrição da issue, foi implementado o filtro de usuários por cargo (admin, suporte e cliente), segue imagens abaixo:

- Todos os usuários:

![image](https://user-images.githubusercontent.com/58437896/171060251-e97bc15c-40e7-4a3b-a8a3-a4987fb92b18.png)

- Todos administradores

![image](https://user-images.githubusercontent.com/58437896/171060292-b87d62e8-486e-4ef4-ae3f-f92348804e60.png)

- Todos suportes

![image](https://user-images.githubusercontent.com/58437896/171060338-16fab8aa-ca9b-487a-80b8-cef094c08d2a.png)

- Todos clientes

![image](https://user-images.githubusercontent.com/58437896/171060348-0ad20dbf-b6df-40e6-a10a-b706a8ca3fdb.png)

### Achou que para por aqui  ? nananinanão

## Foi implementado também a buscar por usuário 😮😲😦😧😨🥵🥶😰😱 

Para o exemplo do funcionamento escolhi filtrar por "ca", onde temos dois usuários com essa informação (gabriel carmargo e caio)


![image](https://user-images.githubusercontent.com/58437896/171060481-c1bc28e3-946b-4fa0-8892-5f410020c227.png)


Como da pra perceber essa busca é feita tanto no nome do usuário como em seu sobrenome, resultando nos itens da imagem acima.

--- 

### Mentira que tu acha que acabou né ? 

Além de fazer um filtro na lista de usuários, todas as outras funcionalidades continuam funcionando 

- Fazendo uma busca e filtrando por cargo (Suporte)

![image](https://user-images.githubusercontent.com/58437896/171060684-09fc0979-a11b-4425-b239-f89e0a23aa70.png)

- Fazendo uma busca e filtrando por cargo (Cliente)

![image](https://user-images.githubusercontent.com/58437896/171060727-de101ff4-b61f-4a3a-b32f-067990526550.png)

- Fazendo uma busca e filtrando por cargo (Admin)

![image](https://user-images.githubusercontent.com/58437896/171060762-15c4df5e-df63-4884-bc33-28161bea3556.png)


---

### Acho que ficou bem claro, a ordenação na lista continua funcionando normalmente 😁😋🥰😎

- Ordenando por nome

![image](https://user-images.githubusercontent.com/58437896/171060839-26294160-222d-487d-b3b6-1e8df1ee5fae.png)
