### ISSUE TITLE
[FRONT] Sistema de possíveis soluções

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-web#95]

**Comment by MariaGabrielaReis** [comment]
<h1 align="center"> Documentação 📄 </h1>

### Tecnologias utilizadas:
As seguintes tecnologias foram utilizadas para o desenvolvimento dessa tarefa: React, HTML, CSS, Visual Studio Code.

### Lista de possíveis soluções (no chamado aberto para suportes):
| Figma | Implementação | 
| :------: | :--------: |
| ![image](https://user-images.githubusercontent.com/69374340/170510894-1c669a90-b77f-490c-9547-adfe80e6e435.png) | ![image](https://user-images.githubusercontent.com/69374340/170510726-493d9052-2743-42b2-9380-e46d2955e2d1.png) |
