### ISSUE TITLE
[FRONT] Adicionar departamento em usuários

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-web#97]
- [x] Adicionar departamento no Cadastro de Equipamento
- [x] Adicionar departamento do usuário na listagem de usuários
- [x]  Admin não pode editar o próprio departamento
- [x] Verificar se está enviando o departamento do cliente no payload de cadastro de ticket
---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by gioliveirass** [comment]
<h1 align="center"> Documentação </h1>

Campo de departamento no registro de equipamentos:

![image](https://user-images.githubusercontent.com/78885451/170765493-d1a4c55c-eb6f-48e0-bb14-c41496be3d29.png)

Campo de departamento no cadastro de usuários:

![image](https://user-images.githubusercontent.com/78885451/170765597-e48859f8-d10b-4689-96e5-c9850ce50367.png)

O departamento do chamado sempre será o mesmo departamento do usuário que o abriu, conforme é possível ver na imagem a seguir:

![image](https://user-images.githubusercontent.com/78885451/170766011-8a3892bc-16cd-4926-91d5-c4a0f0b5eda2.png)

**Tecnologias utilizadas:** CSS, HTML, React.
